#include "defines.h"

struct Habitat
{
	const struct HabitatPage* page;
	u32 numPages;
};

struct HabitatPage
{
	const u16* mons;
	u32 numMons;
};

const u16 gGrasslandPage1[] =
{
	SPECIES_RATTATA,
	SPECIES_RATICATE,
	SPECIES_SENTRET,
	SPECIES_FURRET,
};

const u16 gGrasslandPage2[] =
{
	SPECIES_ZIGZAGOON,
	SPECIES_LINOONE,
	SPECIES_POOCHYENA,
	SPECIES_MIGHTYENA,
};

const u16 gGrasslandPage3[] =
{
	SPECIES_ZIGZAGOON_G,
	SPECIES_LINOONE_G,
	SPECIES_OBSTAGOON,
};

const u16 gGrasslandPage4[] =
{
	SPECIES_NIDORAN_F,
	SPECIES_NIDORINA,
	SPECIES_NIDOQUEEN,
};

const u16 gGrasslandPage5[] =
{
	SPECIES_NIDORAN_M,
	SPECIES_NIDORINO,
	SPECIES_NIDOKING,
};

const u16 gGrasslandPage6[] =
{
	SPECIES_DODUO,
	SPECIES_DODRIO,
	SPECIES_TAILLOW,
	SPECIES_SWELLOW,
};

const u16 gGrasslandPage7[] =
{
	SPECIES_TANGELA,
	SPECIES_TANGROWTH,
	SPECIES_SUNKERN,
	SPECIES_SUNFLORA,
};

const u16 gGrasslandPage8[] =
{
	SPECIES_HOPPIP,
	SPECIES_SKIPLOOM,
	SPECIES_JUMPLUFF,
};

const u16 gGrasslandPage9[] =
{
	SPECIES_ODDISH,
	SPECIES_GLOOM,
	SPECIES_VILEPLUME,
	SPECIES_BELLOSSOM,
};

const u16 gGrasslandPage10[] =
{
	SPECIES_EKANS,
	SPECIES_ARBOK,
	SPECIES_SCYTHER,
	SPECIES_SCIZOR,
};

const u16 gGrasslandPage11[] =
{
	SPECIES_IGGLYBUFF,
	SPECIES_JIGGLYPUFF,
	SPECIES_WIGGLYTUFF,
};

const u16 gGrasslandPage12[] =
{
	SPECIES_MAREEP,
	SPECIES_FLAAFFY,
	SPECIES_AMPHAROS,
};

const u16 gGrasslandPage13[] =
{
	SPECIES_FARFETCHD,
	SPECIES_FARFETCHD_G,
	SPECIES_SIRFETCHD,
};

const u16 gGrasslandPage14[] =
{
	SPECIES_LICKITUNG,
	SPECIES_LICKILICKY,
};

const u16 gGrasslandPage15[] =
{
	SPECIES_BUDEW,
	SPECIES_ROSELIA,
	SPECIES_ROSERADE,
};

const u16 gGrasslandPage16[] =
{
	SPECIES_DROWZEE,
	SPECIES_HYPNO,
	SPECIES_GULPIN,
	SPECIES_SWALOT,
};

const u16 gGrasslandPage17[] =
{
	SPECIES_KANGASKHAN,
	SPECIES_GIRAFARIG,
	SPECIES_TAUROS,
	SPECIES_MILTANK,
};

const u16 gGrasslandPage18[] =
{
	SPECIES_BUNNELBY,
	SPECIES_DIGGERSBY,
	SPECIES_YUNGOOS,
	SPECIES_GUMSHOOS,
};

const u16 gGrasslandPage19[] =
{
	SPECIES_VULPIX,
	SPECIES_NINETALES,
	SPECIES_PONYTA,
	SPECIES_RAPIDASH,
};

const u16 gGrasslandPage20[] =
{
	SPECIES_ELEKID,
	SPECIES_ELECTABUZZ,
	SPECIES_ELECTIVIRE,
};

const u16 gGrasslandPage21[] =
{
	SPECIES_ZANGOOSE,
	SPECIES_SEVIPER,
};

const u16 gGrasslandPage22[] =
{
	SPECIES_ELECTRIKE,
	SPECIES_MANECTRIC,
	SPECIES_PLUSLE,
	SPECIES_MINUN,
};

const u16 gGrasslandPage23[] =
{
	SPECIES_GROWLITHE,
	SPECIES_ARCANINE,
	SPECIES_LITLEO,
	SPECIES_PYROAR,
};

const u16 gGrasslandPage24[] =
{
	SPECIES_CASTFORM,
	SPECIES_CHINGLING,
	SPECIES_CHIMECHO,
};

const u16 gGrasslandPage25[] =
{
	SPECIES_BULBASAUR,
	SPECIES_IVYSAUR,
	SPECIES_VENUSAUR,
};

const u16 gGrasslandPage26[] =
{
	SPECIES_CHIKORITA,
	SPECIES_BAYLEEF,
	SPECIES_MEGANIUM,
};

const u16 gGrasslandPage27[] =
{
	SPECIES_CYNDAQUIL,
	SPECIES_QUILAVA,
	SPECIES_TYPHLOSION,
};

const u16 gGrasslandPage28[] =
{
	SPECIES_TORCHIC,
	SPECIES_COMBUSKEN,
	SPECIES_BLAZIKEN,
};

const u16 gGrasslandPage29[] =
{
	SPECIES_RAIKOU,
	SPECIES_ENTEI,
	SPECIES_SUICUNE,
};

const u16 gGrasslandPage30[] =
{
	SPECIES_TURTWIG,
	SPECIES_GROTLE,
	SPECIES_TORTERRA,
};

const u16 gGrasslandPage31[] =
{
	SPECIES_STARLY,
	SPECIES_STARAVIA,
	SPECIES_STARAPTOR,
};

const u16 gGrasslandPage32[] =
{
	SPECIES_BIDOOF,
	SPECIES_BIBAREL,
	SPECIES_KRICKETOT,
	SPECIES_KRICKETUNE,
};

const u16 gGrasslandPage33[] =
{
	SPECIES_SHINX,
	SPECIES_LUXIO,
	SPECIES_LUXRAY,
	SPECIES_PACHIRISU,
};

const u16 gGrasslandPage34[] =
{
	SPECIES_BUNEARY,
	SPECIES_LOPUNNY,
	SPECIES_GLAMEOW,
	SPECIES_PURUGLY,
};

const u16 gGrasslandPage35[] =
{
	SPECIES_SNIVY,
	SPECIES_SERVINE,
	SPECIES_SERPERIOR,
};

const u16 gGrasslandPage36[] =
{
	SPECIES_PATRAT,
	SPECIES_WATCHOG,
	SPECIES_PURRLOIN,
	SPECIES_LIEPARD,
};

const u16 gGrasslandPage37[] =
{
	SPECIES_LILLIPUP,
	SPECIES_HERDIER,
	SPECIES_STOUTLAND,
	SPECIES_BOUFFALANT,
};

const u16 gGrasslandPage38[] =
{
	SPECIES_BLITZLE,
	SPECIES_ZEBSTRIKA,
	SPECIES_MINCCINO,
	SPECIES_CINCCINO,
};

const u16 gGrasslandPage39[] =
{
	SPECIES_FLETCHLING,
	SPECIES_FLETCHINDER,
	SPECIES_TALONFLAME,
};

const u16 gGrasslandPage40[] =
{
	SPECIES_FLABEBE,
	SPECIES_FLOETTE,
	SPECIES_FLORGES,
	SPECIES_FLOETTE_ETERNAL,
};

const u16 gGrasslandPage41[] =
{
	SPECIES_FLABEBE_BLUE,
	SPECIES_FLOETTE_BLUE,
	SPECIES_FLORGES_BLUE,
};

const u16 gGrasslandPage42[] =
{
	SPECIES_FLABEBE_ORANGE,
	SPECIES_FLOETTE_ORANGE,
	SPECIES_FLORGES_ORANGE,
};

const u16 gGrasslandPage43[] =
{
	SPECIES_FLABEBE_YELLOW,
	SPECIES_FLOETTE_YELLOW,
	SPECIES_FLORGES_YELLOW,
};

const u16 gGrasslandPage44[] =
{
	SPECIES_FLABEBE_WHITE,
	SPECIES_FLOETTE_WHITE,
	SPECIES_FLORGES_WHITE,
};

const u16 gGrasslandPage45[] =
{
	SPECIES_SKIDDO,
	SPECIES_GOGOAT,
	SPECIES_PANCHAM,
	SPECIES_PANGORO,
};

const u16 gGrasslandPage46[] =
{
	SPECIES_FURFROU,
	SPECIES_FURFROU_HEART,
	SPECIES_FURFROU_STAR,
	SPECIES_FURFROU_DIAMOND,
};

const u16 gGrasslandPage47[] =
{
	SPECIES_FURFROU_DEBUTANTE,
	SPECIES_FURFROU_MATRON,
	SPECIES_FURFROU_DANDY,
};

const u16 gGrasslandPage48[] =
{
	SPECIES_FURFROU_LA_REINE,
	SPECIES_FURFROU_KABUKI,
	SPECIES_FURFROU_PHAROAH,
};

const u16 gGrasslandPage49[] =
{
	SPECIES_ESPURR,
	SPECIES_MEOWSTIC,
	SPECIES_MEOWSTIC_FEMALE,
};

const u16 gGrasslandPage50[] =
{
	SPECIES_SPRITZEE,
	SPECIES_AROMATISSE,
	SPECIES_SWIRLIX,
	SPECIES_SLURPUFF,
};

const u16 gGrasslandPage51[] =
{
	SPECIES_PIKIPEK,
	SPECIES_TRUMBEAK,
	SPECIES_TOUCANNON,
};

const u16 gGrasslandPage52[] =
{
	SPECIES_GRUBBIN,
	SPECIES_CHARJABUG,
	SPECIES_VIKAVOLT,
};

const u16 gGrasslandPage53[] =
{
	SPECIES_MUDBRAY,
	SPECIES_MUDSDALE,
	SPECIES_STUFFUL,
	SPECIES_BEWEAR,
};

const u16 gGrasslandPage54[] =
{
	SPECIES_SKWOVET,
	SPECIES_GREEDENT,
	SPECIES_WOOLOO,
	SPECIES_DUBWOOL,
};

const u16 gGrasslandPage55[] =
{
	SPECIES_NICKIT,
	SPECIES_THIEVUL,
	SPECIES_GOSSIFLEUR,
	SPECIES_ELDEGOSS,
};

const u16 gGrasslandPage56[] =
{
	SPECIES_BLIPBUG,
	SPECIES_DOTTLER,
	SPECIES_ORBEETLE,
};

const u16 gGrasslandPage57[] =
{
	SPECIES_YAMPER,
	SPECIES_BOLTUND,
	SPECIES_MORPEKO,
	SPECIES_MORPEKO_HANGRY,
};

const u16 gForestPage1[] =
{
	SPECIES_CATERPIE,
	SPECIES_METAPOD,
	SPECIES_BUTTERFREE,
};

const u16 gForestPage2[] =
{
	SPECIES_WEEDLE,
	SPECIES_KAKUNA,
	SPECIES_BEEDRILL,
};

const u16 gForestPage3[] =
{
	SPECIES_WURMPLE,
	SPECIES_SILCOON,
	SPECIES_BEAUTIFLY,
};

const u16 gForestPage4[] =
{
	SPECIES_CASCOON,
	SPECIES_DUSTOX,
};

const u16 gForestPage5[] =
{
	SPECIES_PIDGEY,
	SPECIES_PIDGEOTTO,
	SPECIES_PIDGEOT,
};

const u16 gForestPage6[] =
{
	SPECIES_HOOTHOOT,
	SPECIES_NOCTOWL,
	SPECIES_NATU,
	SPECIES_XATU,
};

const u16 gForestPage7[] =
{
	SPECIES_PICHU,
	SPECIES_PIKACHU,
	SPECIES_RAICHU,
	SPECIES_RAICHU_A,
};

const u16 gForestPage8[] =
{
	SPECIES_PICHU_SPIKY
};

const u16 gForestPage8_1[] =
{
	SPECIES_PIKACHU_SURFING,
	SPECIES_PIKACHU_FLYING,
};

const u16 gForestPage8_2[] =
{
	SPECIES_PIKACHU_COSPLAY,
	SPECIES_PIKACHU_LIBRE,
	SPECIES_PIKACHU_POP_STAR,
};

const u16 gForestPage8_3[] =
{
	SPECIES_PIKACHU_ROCK_STAR,
	SPECIES_PIKACHU_BELLE,
	SPECIES_PIKACHU_PHD,
};

const u16 gForestPage8_4[] =
{
	SPECIES_PIKACHU_CAP_ORIGINAL,
	SPECIES_PIKACHU_CAP_HOENN,
	SPECIES_PIKACHU_CAP_SINNOH,
	SPECIES_PIKACHU_CAP_UNOVA,
};

const u16 gForestPage8_5[] =
{
	SPECIES_PIKACHU_CAP_KALOS,
	SPECIES_PIKACHU_CAP_ALOLA,
	SPECIES_PIKACHU_CAP_PARTNER,
};

const u16 gForestPage9[] =
{
	SPECIES_BELLSPROUT,
	SPECIES_WEEPINBELL,
	SPECIES_VICTREEBEL,
};

const u16 gForestPage10[] =
{
	SPECIES_PARAS,
	SPECIES_PARASECT,
	SPECIES_SHROOMISH,
	SPECIES_BRELOOM,
};

const u16 gForestPage11[] =
{
	SPECIES_SEEDOT,
	SPECIES_NUZLEAF,
	SPECIES_SHIFTRY,
};

const u16 gForestPage12[] =
{
	SPECIES_VENONAT,
	SPECIES_VENOMOTH,
	SPECIES_YANMA,
	SPECIES_YANMEGA,
};

const u16 gForestPage13[] =
{
	SPECIES_LEDYBA,
	SPECIES_LEDIAN,
	SPECIES_SPINARAK,
	SPECIES_ARIADOS,
};

const u16 gForestPage14[] =
{
	SPECIES_NINCADA,
	SPECIES_NINJASK,
	SPECIES_SHEDINJA,
};

const u16 gForestPage15[] =
{
	SPECIES_VOLBEAT,
	SPECIES_ILLUMISE,
};

const u16 gForestPage16[] =
{
	SPECIES_PINECO,
	SPECIES_FORRETRESS,
};

const u16 gForestPage17[] =
{
	SPECIES_SLAKOTH,
	SPECIES_VIGOROTH,
	SPECIES_SLAKING,
};

const u16 gForestPage18[] =
{
	SPECIES_SKITTY,
	SPECIES_DELCATTY,
};

const u16 gForestPage19[] =
{
	SPECIES_MURKROW,
	SPECIES_HONCHKROW,
	SPECIES_SNEASEL,
	SPECIES_WEAVILE,
};

const u16 gForestPage20[] =
{
	SPECIES_EXEGGCUTE,
	SPECIES_EXEGGUTOR,
	SPECIES_BONSLY,
	SPECIES_SUDOWOODO,
};

const u16 gForestPage21[] =
{
	SPECIES_EXEGGCUTE_A,
	SPECIES_EXEGGUTOR_A,
};

const u16 gForestPage22[] =
{
	SPECIES_AIPOM,
	SPECIES_AMBIPOM,
	SPECIES_STANTLER,
	SPECIES_KECLEON,
};

const u16 gForestPage23[] =
{
	SPECIES_PINSIR,
	SPECIES_HERACROSS,
};

const u16 gForestPage24[] =
{
	SPECIES_SWABLU,
	SPECIES_ALTARIA,
	SPECIES_TROPIUS,
};

const u16 gForestPage25[] =
{
	SPECIES_DUSKULL,
	SPECIES_DUSCLOPS,
	SPECIES_DUSKNOIR,
};

const u16 gForestPage26[] =
{
	SPECIES_TOGEPI,
	SPECIES_TOGETIC,
	SPECIES_TOGEKISS,
};

const u16 gForestPage27[] =
{
	SPECIES_TREECKO,
	SPECIES_GROVYLE,
	SPECIES_SCEPTILE,
};

const u16 gForestPage28[] =
{
	SPECIES_CELEBI,
};

const u16 gForestPage29[] =
{
	SPECIES_CHIMCHAR,
	SPECIES_MONFERNO,
	SPECIES_INFERNAPE,
};

const u16 gForestPage30[] =
{
	SPECIES_BURMY,
	SPECIES_WORMADAM,
	SPECIES_MOTHIM,
	SPECIES_CHATOT,
};

const u16 gForestPage31[] =
{
	SPECIES_BURMY_SANDY,
	SPECIES_BURMY_TRASH,
	SPECIES_WORMADAM_SANDY,
	SPECIES_WORMADAM_TRASH,
};

const u16 gForestPage32[] =
{
	SPECIES_COMBEE,
	SPECIES_VESPIQUEN,
	SPECIES_CHERUBI,
	SPECIES_CHERRIM_SUN,
};

const u16 gForestPage33[] =
{
	SPECIES_DRIFLOON,
	SPECIES_DRIFBLIM,
	SPECIES_STUNKY,
	SPECIES_SKUNTANK,
};

const u16 gForestPage34[] =
{
	SPECIES_CRESSELIA,
	SPECIES_DARKRAI,
	SPECIES_SHAYMIN,
	SPECIES_SHAYMIN_SKY,
};

const u16 gForestPage35[] =
{
	SPECIES_PANSAGE,
	SPECIES_SIMISAGE,
	SPECIES_PANSEAR,
	SPECIES_SIMISEAR,
};

const u16 gForestPage36[] =
{
	SPECIES_PANPOUR,
	SPECIES_SIMIPOUR,
};

const u16 gForestPage37[] =
{
	SPECIES_SEWADDLE,
	SPECIES_SWADLOON,
	SPECIES_LEAVANNY,
};

const u16 gForestPage38[] =
{
	SPECIES_VENIPEDE,
	SPECIES_WHIRLIPEDE,
	SPECIES_SCOLIPEDE,
};

const u16 gForestPage39[] =
{
	SPECIES_COTTONEE,
	SPECIES_WHIMSICOTT,
	SPECIES_PETILIL,
	SPECIES_LILLIGANT,
};

const u16 gForestPage40[] =
{
	SPECIES_ZORUA,
	SPECIES_ZOROARK,
};

const u16 gForestPage41[] =
{
	SPECIES_DEERLING,
	SPECIES_DEERLING_SUMMER,
	SPECIES_DEERLING_AUTUMN,
	SPECIES_DEERLING_WINTER,
};

const u16 gForestPage42[] =
{
	SPECIES_SAWSBUCK,
	SPECIES_SAWSBUCK_SUMMER,
	SPECIES_SAWSBUCK_AUTUMN,
	SPECIES_SAWSBUCK_WINTER,
};

const u16 gForestPage43[] =
{
	SPECIES_KARRABLAST,
	SPECIES_ESCAVALIER,
	SPECIES_FOONGUS,
	SPECIES_AMOONGUSS,
};

const u16 gForestPage44[] =
{
	SPECIES_CHESPIN,
	SPECIES_QUILLADIN,
	SPECIES_CHESNAUGHT,
};

const u16 gForestPage45[] =
{
	SPECIES_SCATTERBUG,
	SPECIES_SPEWPA,
	SPECIES_VIVILLON,
	SPECIES_VIVILLON_ARCHIPELAGO,
};

const u16 gForestPage46[] =
{
	SPECIES_VIVILLON_CONTINENTAL,
	SPECIES_VIVILLON_ELEGANT,
	SPECIES_VIVILLON_GARDEN,
	SPECIES_VIVILLON_HIGH_PLAINS,
};

const u16 gForestPage47[] =
{
	SPECIES_VIVILLON_ICY_SNOW,
	SPECIES_VIVILLON_JUNGLE,
	SPECIES_VIVILLON_MARINE,
	SPECIES_VIVILLON_MODERN,
};

const u16 gForestPage48[] =
{
	SPECIES_VIVILLON_MONSOON,
	SPECIES_VIVILLON_OCEAN,
	SPECIES_VIVILLON_TUNDRA,
	SPECIES_VIVILLON_POLAR,
};

const u16 gForestPage49[] =
{
	SPECIES_VIVILLON_RIVER,
	SPECIES_VIVILLON_SANDSTORM,
	SPECIES_VIVILLON_SAVANNA,
	SPECIES_VIVILLON_SUN,
};

const u16 gForestPage50[] =
{
	SPECIES_VIVILLON_POKEBALL,
	SPECIES_VIVILLON_FANCY,
};

const u16 gForestPage51[] =
{
	SPECIES_EMOLGA,
	SPECIES_HAWLUCHA,
	SPECIES_DEDENNE,
};

const u16 gForestPage52[] =
{
	SPECIES_PHANTUMP,
	SPECIES_TREVENANT,
	SPECIES_PUMPKABOO,
	SPECIES_GOURGEIST,
};

const u16 gForestPage53[] =
{
	SPECIES_PUMPKABOO_M,
	SPECIES_PUMPKABOO_L,
	SPECIES_PUMPKABOO_XL,
};

const u16 gForestPage54[] =
{
	SPECIES_GOURGEIST_M,
	SPECIES_GOURGEIST_L,
	SPECIES_GOURGEIST_XL,
};

const u16 gForestPage55[] =
{
	SPECIES_ROWLET,
	SPECIES_DARTRIX,
	SPECIES_DECIDUEYE,
};

const u16 gForestPage56[] =
{
	SPECIES_ORICORIO,
	SPECIES_ORICORIO_Y,
	SPECIES_ORICORIO_P,
	SPECIES_ORICORIO_S,
};

const u16 gForestPage57[] =
{
	SPECIES_CUTIEFLY,
	SPECIES_RIBOMBEE,
};

const u16 gForestPage58[] =
{
	SPECIES_FOMANTIS,
	SPECIES_LURANTIS,
	SPECIES_MORELULL,
	SPECIES_SHIINOTIC,
};

const u16 gForestPage59[] =
{
	SPECIES_BOUNSWEET,
	SPECIES_STEENEE,
	SPECIES_TSAREENA,
};

const u16 gForestPage60[] =
{
	SPECIES_COMFEY,
	SPECIES_ORANGURU,
	SPECIES_PASSIMIAN,
	SPECIES_KOMALA,
};

const u16 gForestPage61[] =
{
	SPECIES_GROOKEY,
	SPECIES_THWACKEY,
	SPECIES_RILLABOOM,
};

const u16 gForestPage62[] =
{
	SPECIES_APPLIN,
	SPECIES_FLAPPLE,
	SPECIES_APPLETUN,
};

const u16 gForestPage63[] =
{
	SPECIES_PONYTA_G,
	SPECIES_RAPIDASH_G,
	SPECIES_INDEEDEE,
	SPECIES_INDEEDEE_FEMALE,
};

const u16 gForestPage64[] =
{
	SPECIES_HATENNA,
	SPECIES_HATTREM,
	SPECIES_HATTERENE,
};

const u16 gForestPage65[] =
{
	SPECIES_IMPIDIMP,
	SPECIES_MORGREM,
	SPECIES_GRIMMSNARL,
};

const u16 gWatersEdgePage1[] =
{
	SPECIES_GOLDEEN,
	SPECIES_SEAKING,
};

const u16 gWatersEdgePage2[] =
{
	SPECIES_MAGIKARP,
	SPECIES_GYARADOS,
	SPECIES_KRABBY,
	SPECIES_KINGLER,
};

const u16 gWatersEdgePage3[] =
{
	SPECIES_CORPHISH,
	SPECIES_CRAWDAUNT,
	SPECIES_BARBOACH,
	SPECIES_WHISCASH,
};

const u16 gWatersEdgePage4[] =
{
	SPECIES_LOTAD,
	SPECIES_LOMBRE,
	SPECIES_LUDICOLO,
};

const u16 gWatersEdgePage5[] =
{
	SPECIES_SURSKIT,
	SPECIES_MASQUERAIN,
};

const u16 gWatersEdgePage6[] =
{
	SPECIES_PSYDUCK,
	SPECIES_GOLDUCK,
	SPECIES_WOOPER,
	SPECIES_QUAGSIRE,
};

const u16 gWatersEdgePage7[] =
{
	SPECIES_POLIWAG,
	SPECIES_POLIWHIRL,
	SPECIES_POLIWRATH,
	SPECIES_POLITOED,
};

const u16 gWatersEdgePage8[] =
{
	SPECIES_AZURILL,
	SPECIES_MARILL,
	SPECIES_AZUMARILL,
};

const u16 gWatersEdgePage9[] =
{
	SPECIES_SLOWPOKE,
	SPECIES_SLOWBRO,
	SPECIES_SLOWKING,
};

const u16 gWatersEdgePage10[] =
{
	SPECIES_SLOWPOKE_G,
	SPECIES_SLOWBRO_G,
	SPECIES_SLOWKING_G,
};

const u16 gWatersEdgePage11[] =
{
	SPECIES_FEEBAS,
	SPECIES_MILOTIC,
};

const u16 gWatersEdgePage12[] =
{
	SPECIES_ANORITH,
	SPECIES_ARMALDO,
};

const u16 gWatersEdgePage13[] =
{
	SPECIES_DRATINI,
	SPECIES_DRAGONAIR,
	SPECIES_DRAGONITE,
};

const u16 gWatersEdgePage14[] =
{
	SPECIES_SQUIRTLE,
	SPECIES_WARTORTLE,
	SPECIES_BLASTOISE,
};

const u16 gWatersEdgePage15[] =
{
	SPECIES_TOTODILE,
	SPECIES_CROCONAW,
	SPECIES_FERALIGATR,
};

const u16 gWatersEdgePage16[] =
{
	SPECIES_MUDKIP,
	SPECIES_MARSHTOMP,
	SPECIES_SWAMPERT,
};

const u16 gWatersEdgePage17[] =
{
	SPECIES_LATIAS,
	SPECIES_LATIOS,
};

const u16 gWatersEdgePage18[] =
{
	SPECIES_PIPLUP,
	SPECIES_PRINPLUP,
	SPECIES_EMPOLEON,
};

const u16 gWatersEdgePage19[] =
{
	SPECIES_BUIZEL,
	SPECIES_FLOATZEL,
};

const u16 gWatersEdgePage20[] =
{
	SPECIES_SHELLOS,
	SPECIES_GASTRODON,
	SPECIES_SHELLOS_EAST,
	SPECIES_GASTRODON_EAST,
};

const u16 gWatersEdgePage21[] =
{
	SPECIES_FINNEON,
	SPECIES_LUMINEON,
};

const u16 gWatersEdgePage22[] =
{
	SPECIES_OSHAWOTT,
	SPECIES_DEWOTT,
	SPECIES_SAMUROTT,
};

const u16 gWatersEdgePage23[] =
{
	SPECIES_TYMPOLE,
	SPECIES_PALPITOAD,
	SPECIES_SEISMITOAD,
};

const u16 gWatersEdgePage24[] =
{
	SPECIES_BASCULIN_RED,
	SPECIES_BASCULIN_BLUE,
};

const u16 gWatersEdgePage25[] =
{
	SPECIES_DUCKLETT,
	SPECIES_SWANNA,
};

const u16 gWatersEdgePage26[] =
{
	SPECIES_SHELMET,
	SPECIES_ACCELGOR,
	SPECIES_STUNFISK,
	SPECIES_STUNFISK_G,
};

const u16 gWatersEdgePage27[] =
{
	SPECIES_FROAKIE,
	SPECIES_FROGADIER,
	SPECIES_GRENINJA,
	SPECIES_ASHGRENINJA,
};

const u16 gWatersEdgePage28[] =
{
	SPECIES_BINACLE,
	SPECIES_BARBARACLE,
};

const u16 gWatersEdgePage29[] =
{
	SPECIES_SKRELP,
	SPECIES_DRAGALGE,
	SPECIES_CLAUNCHER,
	SPECIES_CLAWITZER,
};

const u16 gWatersEdgePage30[] =
{
	SPECIES_GOOMY,
	SPECIES_SLIGGOO,
	SPECIES_GOODRA,
};

const u16 gWatersEdgePage31[] =
{
	SPECIES_POPPLIO,
	SPECIES_BRIONNE,
	SPECIES_PRIMARINA,
};

const u16 gWatersEdgePage32[] =
{
	SPECIES_DEWPIDER,
	SPECIES_ARAQUANID,
	SPECIES_BRUXISH,
};

const u16 gWatersEdgePage33[] =
{
	SPECIES_WIMPOD,
	SPECIES_GOLISOPOD,
	SPECIES_SANDYGAST,
	SPECIES_PALOSSAND,
};

const u16 gWatersEdgePage34[] =
{
	SPECIES_SOBBLE,
	SPECIES_DRIZZILE,
	SPECIES_INTELEON,
};

const u16 gWatersEdgePage35[] =
{
	SPECIES_CHEWTLE,
	SPECIES_DREDNAW,
	SPECIES_ARROKUDA,
	SPECIES_BARRASKEWDA,
};

const u16 gWatersEdgePage36[] =
{
	SPECIES_CLOBBOPUS,
	SPECIES_GRAPPLOCT,
	SPECIES_PINCURCHIN,
};

const u16 gWatersEdgePage37[] =
{
	SPECIES_EISCUE,
	SPECIES_EISCUE_NOICE,
};

const u16 gWatersEdgePage38[] =
{
	SPECIES_DREEPY,
	SPECIES_DRAKLOAK,
	SPECIES_DRAGAPULT,
};

const u16 gSeaPage1[] =
{
	SPECIES_TENTACOOL,
	SPECIES_TENTACRUEL,
};

const u16 gSeaPage2[] =
{
	SPECIES_WINGULL,
	SPECIES_PELIPPER,
};

const u16 gSeaPage3[] =
{
	SPECIES_STARYU,
	SPECIES_STARMIE,
};

const u16 gSeaPage4[] =
{
	SPECIES_CHINCHOU,
	SPECIES_LANTURN,
	SPECIES_REMORAID,
	SPECIES_OCTILLERY,
};

const u16 gSeaPage5[] =
{
	SPECIES_SHELLDER,
	SPECIES_CLOYSTER,
};

const u16 gSeaPage6[] =
{
	SPECIES_CLAMPERL,
	SPECIES_HUNTAIL,
	SPECIES_GOREBYSS,
};

const u16 gSeaPage7[] =
{
	SPECIES_QWILFISH,
	SPECIES_CORSOLA,
	SPECIES_CORSOLA_G,
	SPECIES_CURSOLA,
};

const u16 gSeaPage8[] =
{
	SPECIES_SEEL,
	SPECIES_DEWGONG,
	SPECIES_MANTYKE,
	SPECIES_MANTINE,
};

const u16 gSeaPage9[] =
{
	SPECIES_SPHEAL,
	SPECIES_SEALEO,
	SPECIES_WALREIN,
};

const u16 gSeaPage10[] =
{
	SPECIES_CARVANHA,
	SPECIES_SHARPEDO,
	SPECIES_WAILMER,
	SPECIES_WAILORD,
};

const u16 gSeaPage11[] =
{
	SPECIES_HORSEA,
	SPECIES_SEADRA,
	SPECIES_KINGDRA,
};

const u16 gSeaPage12[] =
{
	SPECIES_LUVDISC,
	SPECIES_RELICANTH,
};

const u16 gSeaPage13[] =
{
	SPECIES_LAPRAS,
};

const u16 gSeaPage14[] =
{
	SPECIES_OMANYTE,
	SPECIES_OMASTAR,
	SPECIES_KABUTO,
	SPECIES_KABUTOPS,
};

const u16 gSeaPage15[] =
{
	SPECIES_LILEEP,
	SPECIES_CRADILY,
};

const u16 gSeaPage16[] =
{
	SPECIES_KYOGRE,
};

const u16 gSeaPage17[] =
{
	SPECIES_MANAPHY,
	SPECIES_PHIONE,
};

const u16 gSeaPage18[] =
{
	SPECIES_TIRTOUGA,
	SPECIES_CARRACOSTA,
	SPECIES_DRACOVISH,
	SPECIES_ARCTOVISH,
};

const u16 gSeaPage19[] =
{
	SPECIES_FRILLISH,
	SPECIES_JELLICENT,
	SPECIES_ALOMOMOLA,
	SPECIES_DHELMISE,
};

const u16 gSeaPage20[] =
{
	SPECIES_WISHIWASHI,
	SPECIES_WISHIWASHI_S,
};

const u16 gSeaPage21[] =
{
	SPECIES_MAREANIE,
	SPECIES_TOXAPEX,
	SPECIES_PYUKUMUKU,
};

const u16 gSeaPage22[] =
{
	SPECIES_CRAMORANT,
	SPECIES_CRAMORANT_GULPING,
	SPECIES_CRAMORANT_GORGING,
};

const u16 gCavePage1[] =
{
	SPECIES_ZUBAT,
	SPECIES_GOLBAT,
	SPECIES_CROBAT,
};

const u16 gCavePage2[] =
{
	SPECIES_DIGLETT,
	SPECIES_DUGTRIO,
	SPECIES_ONIX,
	SPECIES_STEELIX,
};

const u16 gCavePage3[] =
{
	SPECIES_DIGLETT_A,
	SPECIES_DUGTRIO_A,
};

const u16 gCavePage4[] =
{
	SPECIES_SWINUB,
	SPECIES_PILOSWINE,
	SPECIES_MAMOSWINE,
};

const u16 gCavePage5[] =
{
	SPECIES_SNORUNT,
	SPECIES_GLALIE,
	SPECIES_FROSLASS,
};

const u16 gCavePage6[] =
{
	SPECIES_WHISMUR,
	SPECIES_LOUDRED,
	SPECIES_EXPLOUD,
};

const u16 gCavePage7[] =
{
	SPECIES_MISDREAVUS,
	SPECIES_MISMAGIUS,
	SPECIES_DUNSPARCE,
};

const u16 gCavePage8[] =
{
	SPECIES_NOSEPASS,
	SPECIES_PROBOPASS,
};

const u16 gCavePage9[] =
{
	SPECIES_SABLEYE,
	SPECIES_MAWILE,
};

const u16 gCavePage10[] =
{
	SPECIES_GASTLY,
	SPECIES_HAUNTER,
	SPECIES_GENGAR,
};

const u16 gCavePage11[] =
{
	SPECIES_WYNAUT,
	SPECIES_WOBBUFFET,
};

const u16 gCavePage12[] =
{
	SPECIES_LUNATONE,
	SPECIES_SOLROCK,
};

const u16 gCavePage13[] =
{
	SPECIES_REGIROCK,
	SPECIES_REGICE,
	SPECIES_REGISTEEL,
};

const u16 gCavePage14[] =
{
	SPECIES_CRANIDOS,
	SPECIES_RAMPARDOS,
	SPECIES_SHIELDON,
	SPECIES_BASTIODON,
};

const u16 gCavePage15[] =
{
	SPECIES_BRONZOR,
	SPECIES_BRONZONG,
};

const u16 gCavePage16[] =
{
	SPECIES_GIBLE,
	SPECIES_GABITE,
	SPECIES_GARCHOMP,
};

const u16 gCavePage17[] =
{
	SPECIES_UXIE,
	SPECIES_MESPRIT,
	SPECIES_AZELF,
};

const u16 gCavePage18[] =
{
	SPECIES_HEATRAN,
	SPECIES_REGIGIGAS,
};

const u16 gCavePage19[] =
{
	SPECIES_ROGGENROLA,
	SPECIES_BOLDORE,
	SPECIES_GIGALITH,
};

const u16 gCavePage20[] =
{
	SPECIES_WOOBAT,
	SPECIES_SWOOBAT,
	SPECIES_DRILBUR,
	SPECIES_EXCADRILL,
};

const u16 gCavePage21[] =
{
	SPECIES_JOLTIK,
	SPECIES_GALVANTULA,
	SPECIES_FERROSEED,
	SPECIES_FERROTHORN,
};

const u16 gCavePage22[] =
{
	SPECIES_KLINK,
	SPECIES_KLANG,
	SPECIES_KLINKLANG,
};

const u16 gCavePage23[] =
{
	SPECIES_TYNAMO,
	SPECIES_EELEKTRIK,
	SPECIES_EELEKTROSS,
};

const u16 gCavePage24[] =
{
	SPECIES_AXEW,
	SPECIES_FRAXURE,
	SPECIES_HAXORUS,
};

const u16 gCavePage25[] =
{
	SPECIES_CUBCHOO,
	SPECIES_BEARTIC,
	SPECIES_CRYOGONAL,
};

const u16 gCavePage26[] =
{
	SPECIES_DEINO,
	SPECIES_ZWEILOUS,
	SPECIES_HYDREIGON,
};

const u16 gCavePage27[] =
{
	SPECIES_LARVESTA,
	SPECIES_VOLCARONA,
};

const u16 gCavePage28[] =
{
	SPECIES_COBALION,
	SPECIES_TERRAKION,
	SPECIES_VIRIZION,
};

const u16 gCavePage29[] =
{
	SPECIES_KELDEO,
	SPECIES_KELDEO_RESOLUTE,
};

const u16 gCavePage30[] =
{
	SPECIES_BERGMITE,
	SPECIES_AVALUGG,
	SPECIES_CARBINK,
	SPECIES_DIANCIE,
};

const u16 gCavePage31[] =
{
	SPECIES_ZYGARDE_10,
	SPECIES_ZYGARDE,
	SPECIES_ZYGARDE_COMPLETE,
};

const u16 gCavePage32[] =
{
	SPECIES_JANGMO_O,
	SPECIES_HAKAMO_O,
	SPECIES_KOMMO_O,
};

const u16 gCavePage33[] =
{
	SPECIES_TAPU_KOKO,
	SPECIES_TAPU_LELE,
	SPECIES_TAPU_BULU,
	SPECIES_TAPU_FINI,
};

const u16 gCavePage34[] =
{
	SPECIES_ROLYCOLY,
	SPECIES_CARKOL,
	SPECIES_COALOSSAL,
};

const u16 gCavePage35[] =
{
	SPECIES_REGIELEKI,
	SPECIES_REGIDRAGO,
};

const u16 gMountainPage1[] =
{
	SPECIES_GEODUDE,
	SPECIES_GRAVELER,
	SPECIES_GOLEM,
};

const u16 gMountainPage2[] =
{
	SPECIES_GEODUDE_A,
	SPECIES_GRAVELER_A,
	SPECIES_GOLEM_A,
};

const u16 gMountainPage3[] =
{
	SPECIES_MANKEY,
	SPECIES_PRIMEAPE,
	SPECIES_SPOINK,
	SPECIES_GRUMPIG,
};

const u16 gMountainPage4[] =
{
	SPECIES_MACHOP,
	SPECIES_MACHOKE,
	SPECIES_MACHAMP,
};

const u16 gMountainPage5[] =
{
	SPECIES_CLEFFA,
	SPECIES_CLEFAIRY,
	SPECIES_CLEFABLE,
};

const u16 gMountainPage6[] =
{
	SPECIES_CUBONE,
	SPECIES_MAROWAK,
	SPECIES_CUBONE_A,
	SPECIES_MAROWAK_A,
};

const u16 gMountainPage7[] =
{
	SPECIES_ARTICUNO,
	SPECIES_ZAPDOS,
	SPECIES_MOLTRES,
};

const u16 gMountainPage8[] =
{
	SPECIES_ARTICUNO_G,
	SPECIES_ZAPDOS_G,
	SPECIES_MOLTRES_G,
};

const u16 gMountainPage9[] =
{
	SPECIES_SLUGMA,
	SPECIES_MAGCARGO,
	SPECIES_NUMEL,
	SPECIES_CAMERUPT,
};

const u16 gMountainPage10[] =
{
	SPECIES_MAKUHITA,
	SPECIES_HARIYAMA,
	SPECIES_MEDITITE,
	SPECIES_MEDICHAM,
};

const u16 gMountainPage11[] =
{
	SPECIES_SHUCKLE,
	SPECIES_TEDDIURSA,
	SPECIES_URSARING,
	SPECIES_DELIBIRD,
};

const u16 gMountainPage12[] =
{
	SPECIES_GLIGAR,
	SPECIES_GLISCOR,
	SPECIES_SPINDA,
};

const u16 gMountainPage13[] =
{
	SPECIES_MAGBY,
	SPECIES_MAGMAR,
	SPECIES_MAGMORTAR,
	SPECIES_TORKOAL,
};

const u16 gMountainPage14[] =
{
	SPECIES_ARON,
	SPECIES_LAIRON,
	SPECIES_AGGRON,
};

const u16 gMountainPage15[] =
{
	SPECIES_LARVITAR,
	SPECIES_PUPITAR,
	SPECIES_TYRANITAR,
};

const u16 gMountainPage16[] =
{
	SPECIES_MUNCHLAX,
	SPECIES_SNORLAX,
};

const u16 gMountainPage17[] =
{
	SPECIES_VULPIX_A,
	SPECIES_NINETALES_A,
	SPECIES_ABSOL,
};

const u16 gMountainPage18[] =
{
	SPECIES_SANDSHREW_A,
	SPECIES_SANDSLASH_A,
	SPECIES_AERODACTYL,
};

const u16 gMountainPage19[] =
{
	SPECIES_MUNCHLAX,
	SPECIES_SNORLAX,
};

const u16 gMountainPage20[] =
{
	SPECIES_CHARMANDER,
	SPECIES_CHARMELEON,
	SPECIES_CHARIZARD,
};

const u16 gMountainPage21[] =
{
	SPECIES_JIRACHI,
};

const u16 gMountainPage22[] =
{
	SPECIES_RIOLU,
	SPECIES_LUCARIO,
	SPECIES_CROAGUNK,
	SPECIES_TOXICROAK,
};

const u16 gMountainPage23[] =
{
	SPECIES_CARNIVINE,
	SPECIES_SNOVER,
	SPECIES_ABOMASNOW,
};

const u16 gMountainPage24[] =
{
	SPECIES_TIMBURR,
	SPECIES_GURDURR,
	SPECIES_CONKELDURR,
};

const u16 gMountainPage25[] =
{
	SPECIES_THROH,
	SPECIES_SAWK,
};

const u16 gMountainPage26[] =
{
	SPECIES_ARCHEN,
	SPECIES_ARCHEOPS,
};

const u16 gMountainPage27[] =
{
	SPECIES_VANILLITE,
	SPECIES_VANILLISH,
	SPECIES_VANILLUXE,
};

const u16 gMountainPage28[] =
{
	SPECIES_MIENFOO,
	SPECIES_MIENSHAO,
	SPECIES_DRUDDIGON,
};

const u16 gMountainPage29[] =
{
	SPECIES_RUFFLET,
	SPECIES_BRAVIARY,
	SPECIES_VULLABY,
	SPECIES_MANDIBUZZ,
};

const u16 gMountainPage30[] =
{
	SPECIES_HEATMOR,
	SPECIES_DURANT,
};

const u16 gMountainPage31[] =
{
	SPECIES_INKAY,
	SPECIES_MALAMAR,
};

const u16 gMountainPage32[] =
{
	SPECIES_TYRUNT,
	SPECIES_TYRANTRUM,
	SPECIES_AMAURA,
	SPECIES_AURORUS,
};

const u16 gMountainPage33[] =
{
	SPECIES_NOIBAT,
	SPECIES_NOIVERN,
};

const u16 gMountainPage34[] =
{
	SPECIES_XERNEAS,
	SPECIES_YVELTAL,
};

const u16 gMountainPage35[] =
{
	SPECIES_CRABRAWLER,
	SPECIES_CRABOMINABLE,
};

const u16 gMountainPage36[] =
{
	SPECIES_ROCKRUFF,
	SPECIES_LYCANROC,
	SPECIES_LYCANROC_N,
	SPECIES_LYCANROC_DUSK,
};

const u16 gMountainPage37[] =
{
	SPECIES_SALANDIT,
	SPECIES_SALAZZLE,
};

const u16 gMountainPage38[] =
{
	SPECIES_TURTONATOR,
	SPECIES_TOGEDEMARU,
	SPECIES_DRAMPA,
};

const u16 gMountainPage39[]=
{
	SPECIES_MINIOR_SHIELD,
	SPECIES_MINIOR_RED,
	SPECIES_MINIOR_BLUE,
	SPECIES_MINIOR_ORANGE,
};

const u16 gMountainPage40[]=
{
	SPECIES_MINIOR_YELLOW,
	SPECIES_MINIOR_INDIGO,
	SPECIES_MINIOR_GREEN,
};

const u16 gMountainPage41[] =
{
	SPECIES_ZERAORA,
};

const u16 gMountainPage42[] =
{
	SPECIES_STONJOURNER,
	SPECIES_CUFANT,
	SPECIES_COPPERAJAH,
	SPECIES_DURALUDON,
};

const u16 gMountainPage43[] =
{
	SPECIES_SNOM,
	SPECIES_FROSMOTH,
};

const u16 gRoughTerrainPage1[] =
{
	SPECIES_SPEAROW,
	SPECIES_FEAROW,
};

const u16 gRoughTerrainPage2[] =
{
	SPECIES_SANDSHREW,
	SPECIES_SANDSLASH,
};

const u16 gRoughTerrainPage3[] =
{
	SPECIES_RHYHORN,
	SPECIES_RHYDON,
	SPECIES_RHYPERIOR,
};

const u16 gRoughTerrainPage4[] =
{
	SPECIES_MAGNEMITE,
	SPECIES_MAGNETON,
	SPECIES_MAGNEZONE,
};

const u16 gRoughTerrainPage5[] =
{
	SPECIES_HOUNDOUR,
	SPECIES_HOUNDOOM,
	SPECIES_PHANPY,
	SPECIES_DONPHAN,
};

const u16 gRoughTerrainPage6[] =
{
	SPECIES_CACNEA,
	SPECIES_CACTURNE,
};

const u16 gRoughTerrainPage7[] =
{
	SPECIES_TRAPINCH,
	SPECIES_VIBRAVA,
	SPECIES_FLYGON,
};

const u16 gRoughTerrainPage8[] =
{
	SPECIES_SKARMORY,
};

const u16 gRoughTerrainPage9[] =
{
	SPECIES_BALTOY,
	SPECIES_CLAYDOL,
};

const u16 gRoughTerrainPage10[] =
{
	SPECIES_BAGON,
	SPECIES_SHELGON,
	SPECIES_SALAMENCE,
};

const u16 gRoughTerrainPage11[] =
{
	SPECIES_BELDUM,
	SPECIES_METANG,
	SPECIES_METAGROSS,
};

const u16 gRoughTerrainPage12[] =
{
	SPECIES_GROUDON,
};

const u16 gRoughTerrainPage13[] =
{
	SPECIES_HIPPOPOTAS,
	SPECIES_HIPPOWDON,
};

const u16 gRoughTerrainPage14[] =
{
	SPECIES_SKORUPI,
	SPECIES_DRAPION,
};

const u16 gRoughTerrainPage15[] =
{
	SPECIES_SANDILE,
	SPECIES_KROKOROK,
	SPECIES_KROOKODILE,
};

const u16 gRoughTerrainPage16[] =
{
	SPECIES_MARACTUS,
	SPECIES_DARUMAKA,
	SPECIES_DARMANITAN,
	SPECIES_DARMANITANZEN,

};

const u16 gRoughTerrainPage17[] =
{
	SPECIES_DARUMAKA_G,
	SPECIES_DARMANITAN_G,
	SPECIES_DARMANITAN_G_ZEN,
};

const u16 gRoughTerrainPage18[] =
{
	SPECIES_SCRAGGY,
	SPECIES_SCRAFTY,
	SPECIES_DWEBBLE,
	SPECIES_CRUSTLE,
};

const u16 gRoughTerrainPage19[] =
{
	SPECIES_SIGILYPH,
	SPECIES_YAMASK,
	SPECIES_COFAGRIGUS,
};

const u16 gRoughTerrainPage20[] =
{
	SPECIES_YAMASK_G,
	SPECIES_RUNERIGUS,
};

const u16 gRoughTerrainPage21[] =
{
	SPECIES_GOLETT,
	SPECIES_GOLURK,
	SPECIES_PAWNIARD,
	SPECIES_BISHARP,
};

const u16 gRoughTerrainPage22[] =
{
	SPECIES_HONEDGE,
	SPECIES_DOUBLADE,
	SPECIES_AEGISLASH,
	SPECIES_AEGISLASH_BLADE,
};

const u16 gRoughTerrainPage23[] =
{
	SPECIES_HELIOPTILE,
	SPECIES_HELIOLISK,
};

const u16 gRoughTerrainPage24[] =
{
	SPECIES_HOOPA,
	SPECIES_HOOPA_UNBOUND,
	SPECIES_VOLCANION,
};

const u16 gRoughTerrainPage25[] =
{
	SPECIES_ROOKIDEE,
	SPECIES_CORVISQUIRE,
	SPECIES_CORVIKNIGHT,
};

const u16 gRoughTerrainPage26[] =
{
	SPECIES_MEOWTH_G,
	SPECIES_PERRSERKER,
	SPECIES_FALINKS,
};

const u16 gRoughTerrainPage27[] =
{
	SPECIES_SIZZLIPEDE,
	SPECIES_CENTISKORCH,
	SPECIES_SILICOBRA,
	SPECIES_SANDACONDA,
};

const u16 gRoughTerrainPage28[] =
{
	SPECIES_DRACOZOLT,
	SPECIES_ARCTOZOLT,
};

const u16 gUrbanPage1[] =
{
	SPECIES_MEOWTH,
	SPECIES_PERSIAN,
	SPECIES_SNUBBULL,
	SPECIES_GRANBULL,
};

const u16 gUrbanPage2[] =
{
	SPECIES_RATTATA_A,
	SPECIES_RATICATE_A,
	SPECIES_MEOWTH_A,
	SPECIES_PERSIAN_A,
};

const u16 gUrbanPage3[] =
{
	SPECIES_GRIMER,
	SPECIES_MUK,
	SPECIES_KOFFING,
	SPECIES_WEEZING,
};

const u16 gUrbanPage4[] =
{
	SPECIES_GRIMER_A,
	SPECIES_MUK_A,
	SPECIES_KOFFING_G,
	SPECIES_WEEZING_G,
};

const u16 gUrbanPage5[] =
{
	SPECIES_SHUPPET,
	SPECIES_BANETTE,
};

const u16 gUrbanPage6[] =
{
	SPECIES_ABRA,
	SPECIES_KADABRA,
	SPECIES_ALAKAZAM,
};

const u16 gUrbanPage7[] =
{
	SPECIES_RALTS,
	SPECIES_KIRLIA,
	SPECIES_GARDEVOIR,
	SPECIES_GALLADE,
};

const u16 gUrbanPage8[] =
{
	SPECIES_SMOOCHUM,
	SPECIES_JYNX,
	SPECIES_SMEARGLE,
};

const u16 gUrbanPage9[] =
{
	SPECIES_MIME_JR,
	SPECIES_MR_MIME,
};

const u16 gUrbanPage10[] =
{
	SPECIES_MIME_JR_G,
	SPECIES_MR_MIME_G,
	SPECIES_MR_RIME,
};

const u16 gUrbanPage11[] =
{
	SPECIES_TYROGUE,
	SPECIES_HITMONLEE,
	SPECIES_HITMONCHAN,
	SPECIES_HITMONTOP,
};

const u16 gUrbanPage12[] =
{
	SPECIES_HAPPINY,
	SPECIES_CHANSEY,
	SPECIES_BLISSEY,
};

const u16 gUrbanPage13[] =
{
	SPECIES_VOLTORB,
	SPECIES_ELECTRODE,
};

const u16 gUrbanPage14[] =
{
	SPECIES_PORYGON,
	SPECIES_PORYGON2,
	SPECIES_PORYGON_Z,
};

const u16 gUrbanPage15[] =
{
	SPECIES_DITTO,
};

const u16 gUrbanPage16[] =
{
	SPECIES_EEVEE,
	SPECIES_VAPOREON,
	SPECIES_JOLTEON,
	SPECIES_FLAREON,
};

const u16 gUrbanPage17[] =
{
	SPECIES_ESPEON,
	SPECIES_UMBREON,
};

const u16 gUrbanPage18[] =
{
	SPECIES_LEAFEON,
	SPECIES_GLACEON,
	SPECIES_SYLVEON,
};

const u16 gUrbanPage19[] =
{
	SPECIES_ROTOM,
	SPECIES_ROTOM_HEAT,
	SPECIES_ROTOM_WASH,
};

const u16 gUrbanPage20[] =
{
	SPECIES_ROTOM_FROST,
	SPECIES_ROTOM_FAN,
	SPECIES_ROTOM_MOW,
};

const u16 gUrbanPage21[] =
{
	SPECIES_TEPIG,
	SPECIES_PIGNITE,
	SPECIES_EMBOAR,
};

const u16 gUrbanPage22[] =
{
	SPECIES_MUNNA,
	SPECIES_MUSHARNA,
	SPECIES_AUDINO,
};

const u16 gUrbanPage23[] =
{
	SPECIES_PIDOVE,
	SPECIES_TRANQUILL,
	SPECIES_UNFEZANT,
};

const u16 gUrbanPage24[] =
{
	SPECIES_TRUBBISH,
	SPECIES_GARBODOR,
};

const u16 gUrbanPage25[] =
{
	SPECIES_GOTHITA,
	SPECIES_GOTHORITA,
	SPECIES_GOTHITELLE,
};

const u16 gUrbanPage26[] =
{
	SPECIES_SOLOSIS,
	SPECIES_DUOSION,
	SPECIES_REUNICLUS,
};

const u16 gUrbanPage27[] =
{
	SPECIES_ELGYEM,
	SPECIES_BEHEEYEM,
};

const u16 gUrbanPage28[] =
{
	SPECIES_LITWICK,
	SPECIES_LAMPENT,
	SPECIES_CHANDELURE,
};

const u16 gUrbanPage29[] =
{
	SPECIES_FENNEKIN,
	SPECIES_BRAIXEN,
	SPECIES_DELPHOX,
};

const u16 gUrbanPage30[] =
{
	SPECIES_KLEFKI,
	SPECIES_MIMIKYU,
	SPECIES_MIMIKYU_BUSTED,
};

const u16 gUrbanPage31[] =
{
	SPECIES_LITTEN,
	SPECIES_TORRACAT,
	SPECIES_INCINEROAR,
};

const u16 gUrbanPage32[] =
{
	SPECIES_SCORBUNNY,
	SPECIES_RABOOT,
	SPECIES_CINDERACE,
};

const u16 gUrbanPage33[] =
{
	SPECIES_TOXEL,
	SPECIES_TOXTRICITY,
	SPECIES_TOXTRICITY_LOW_KEY,
};

const u16 gUrbanPage34[] =
{
	SPECIES_SINISTEA,
	SPECIES_POLTEAGEIST,
	SPECIES_SINISTEA_CHIPPED,
	SPECIES_POLTEAGEIST_CHIPPED,
};

const u16 gUrbanPage35[] =
{
	SPECIES_MILCERY,
	SPECIES_ALCREMIE_STRAWBERRY,
};

const u16 gUrbanPage36[] =
{
	SPECIES_ALCREMIE_BERRY,
	SPECIES_ALCREMIE_CLOVER,
	SPECIES_ALCREMIE_FLOWER,
};

const u16 gUrbanPage37[] =
{
	SPECIES_ALCREMIE_LOVE,
	SPECIES_ALCREMIE_RIBBON,
	SPECIES_ALCREMIE_STAR,
};

const u16 gRarePage1[] =
{
	SPECIES_UNOWN,
};

const u16 gRarePage2[] =
{
	SPECIES_LUGIA,
	SPECIES_HO_OH,
};

const u16 gRarePage3[] =
{
	SPECIES_RAYQUAZA,
};

const u16 gRarePage4[] =
{
	SPECIES_DEOXYS,
	SPECIES_DEOXYS_ATTACK,
	SPECIES_DEOXYS_DEFENSE,
	SPECIES_DEOXYS_SPEED,
};

const u16 gRarePage5[] =
{
	SPECIES_MEWTWO,
	SPECIES_MEW,
};

const u16 gRarePage6[] =
{
	SPECIES_SPIRITOMB,
};

const u16 gRarePage7[] =
{
	SPECIES_DIALGA,
	SPECIES_PALKIA,
	SPECIES_GIRATINA,
	SPECIES_GIRATINA_ORIGIN,
};

const u16 gRarePage8[] =
{
	SPECIES_ARCEUS,
	SPECIES_ARCEUS_FIRE,
	SPECIES_ARCEUS_WATER,
	SPECIES_ARCEUS_GRASS,
};

const u16 gRarePage9[] =
{
	SPECIES_ARCEUS_ELECTRIC,
	SPECIES_ARCEUS_ICE,
	SPECIES_ARCEUS_FIGHT,
	SPECIES_ARCEUS_POISON,
};

const u16 gRarePage10[] =
{
	SPECIES_ARCEUS_GROUND,
	SPECIES_ARCEUS_FLYING,
	SPECIES_ARCEUS_PSYCHIC,
	SPECIES_ARCEUS_BUG,
};

const u16 gRarePage11[] =
{
	SPECIES_ARCEUS_ROCK,
	SPECIES_ARCEUS_GHOST,
	SPECIES_ARCEUS_DRAGON,
};

const u16 gRarePage12[] =
{
	SPECIES_ARCEUS_DARK,
	SPECIES_ARCEUS_STEEL,
	SPECIES_ARCEUS_FAIRY,
};

const u16 gRarePage13[] =
{
	SPECIES_VICTINI,
};

const u16 gRarePage14[] =
{
	SPECIES_TORNADUS,
	SPECIES_THUNDURUS,
	SPECIES_LANDORUS,
};

const u16 gRarePage15[] =
{
	SPECIES_TORNADUS_THERIAN,
	SPECIES_THUNDURUS_THERIAN,
	SPECIES_LANDORUS_THERIAN,
};

const u16 gRarePage16[] =
{
	SPECIES_RESHIRAM,
	SPECIES_ZEKROM,
};

const u16 gRarePage17[] =
{
	SPECIES_KYUREM,
	SPECIES_KYUREM_BLACK,
	SPECIES_KYUREM_WHITE,
};

const u16 gRarePage18[] =
{
	SPECIES_MELOETTA,
	SPECIES_MELOETTA_PIROUETTE,
	SPECIES_GENESECT,
};

const u16 gRarePage19[] =
{
	SPECIES_GENESECT_SHOCK,
	SPECIES_GENESECT_BURN,
	SPECIES_GENESECT_CHILL,
	SPECIES_GENESECT_DOUSE,
};

const u16 gRarePage20[] =
{
	SPECIES_TYPE_NULL,
	SPECIES_SILVALLY,
	SPECIES_SILVALLY_FIGHT,
	SPECIES_SILVALLY_FLYING,
};

const u16 gRarePage21[] =
{
	SPECIES_SILVALLY_POISON,
	SPECIES_SILVALLY_GROUND,
	SPECIES_SILVALLY_ROCK,
	SPECIES_SILVALLY_BUG,
};

const u16 gRarePage22[] =
{
	SPECIES_SILVALLY_GHOST,
	SPECIES_SILVALLY_STEEL,
	SPECIES_SILVALLY_FIRE,
	SPECIES_SILVALLY_WATER,
};

const u16 gRarePage23[] =
{
	SPECIES_SILVALLY_GRASS,
	SPECIES_SILVALLY_ELECTRIC,
	SPECIES_SILVALLY_PSYCHIC,
	SPECIES_SILVALLY_ICE,
};

const u16 gRarePage24[] =
{
	SPECIES_SILVALLY_DRAGON,
	SPECIES_SILVALLY_DARK,
	SPECIES_SILVALLY_FAIRY,
};

const u16 gRarePage25[] =
{
	SPECIES_COSMOG,
	SPECIES_COSMOEM,
	SPECIES_SOLGALEO,
	SPECIES_LUNALA,
};

const u16 gRarePage26[] =
{
	SPECIES_NIHILEGO,
	SPECIES_BUZZWOLE,
	SPECIES_PHEROMOSA,
	SPECIES_XURKITREE,
};

const u16 gRarePage27[] =
{
	SPECIES_CELESTEELA,
	SPECIES_KARTANA,
	SPECIES_GUZZLORD,
};

const u16 gRarePage28[] =
{
	SPECIES_NECROZMA,
	SPECIES_NECROZMA_DUSK_MANE,
	SPECIES_NECROZMA_DAWN_WINGS,
	SPECIES_NECROZMA_ULTRA,
};

const u16 gRarePage29[] =
{
	SPECIES_MAGEARNA,
	SPECIES_MAGEARNA_P,
	SPECIES_MARSHADOW,
};

const u16 gRarePage30[] =
{
	SPECIES_POIPOLE,
	SPECIES_NAGANADEL,
	SPECIES_STAKATAKA,
	SPECIES_BLACEPHALON,
};

const u16 gRarePage31[] =
{
	SPECIES_MELTAN,
	SPECIES_MELMETAL,
};

const u16 gRarePage32[] =
{
	SPECIES_ZACIAN,
	SPECIES_ZACIAN_CROWNED,
	SPECIES_ZAMAZENTA,
	SPECIES_ZAMAZENTA_CROWNED,
};

const u16 gRarePage33[] =
{
	SPECIES_ETERNATUS,
	SPECIES_ETERNATUS_ETERNAMAX,
	SPECIES_ZARUDE,
	SPECIES_CALYREX,
};

const u16 gRarePage34[] =
{
	SPECIES_KUBFU,
	SPECIES_URSHIFU_SINGLE,
	SPECIES_URSHIFU_RAPID,
	SPECIES_UNKNOWN_MYTHICAL,
};

const struct HabitatPage gGrasslandPages[] =
{
	{gGrasslandPage1, ARRAY_COUNT(gGrasslandPage1)}, 
	{gGrasslandPage2, ARRAY_COUNT(gGrasslandPage2)}, 
	{gGrasslandPage3, ARRAY_COUNT(gGrasslandPage3)}, 
	{gGrasslandPage4, ARRAY_COUNT(gGrasslandPage4)}, 
	{gGrasslandPage5, ARRAY_COUNT(gGrasslandPage5)}, 
	{gGrasslandPage6, ARRAY_COUNT(gGrasslandPage6)}, 
	{gGrasslandPage7, ARRAY_COUNT(gGrasslandPage7)}, 
	{gGrasslandPage8, ARRAY_COUNT(gGrasslandPage8)}, 
	{gGrasslandPage9, ARRAY_COUNT(gGrasslandPage9)}, 
	{gGrasslandPage10, ARRAY_COUNT(gGrasslandPage10)}, 
	{gGrasslandPage11, ARRAY_COUNT(gGrasslandPage11)}, 
	{gGrasslandPage12, ARRAY_COUNT(gGrasslandPage12)}, 
	{gGrasslandPage13, ARRAY_COUNT(gGrasslandPage13)}, 
	{gGrasslandPage14, ARRAY_COUNT(gGrasslandPage14)}, 
	{gGrasslandPage15, ARRAY_COUNT(gGrasslandPage15)}, 
	{gGrasslandPage16, ARRAY_COUNT(gGrasslandPage16)}, 
	{gGrasslandPage17, ARRAY_COUNT(gGrasslandPage17)}, 
	{gGrasslandPage18, ARRAY_COUNT(gGrasslandPage18)}, 
	{gGrasslandPage19, ARRAY_COUNT(gGrasslandPage19)}, 
	{gGrasslandPage20, ARRAY_COUNT(gGrasslandPage20)}, 
	{gGrasslandPage21, ARRAY_COUNT(gGrasslandPage21)}, 
	{gGrasslandPage22, ARRAY_COUNT(gGrasslandPage22)}, 
	{gGrasslandPage23, ARRAY_COUNT(gGrasslandPage23)}, 
	{gGrasslandPage24, ARRAY_COUNT(gGrasslandPage24)}, 
	{gGrasslandPage25, ARRAY_COUNT(gGrasslandPage25)}, 
	{gGrasslandPage26, ARRAY_COUNT(gGrasslandPage26)}, 
	{gGrasslandPage27, ARRAY_COUNT(gGrasslandPage27)}, 
	{gGrasslandPage28, ARRAY_COUNT(gGrasslandPage28)}, 
	{gGrasslandPage29, ARRAY_COUNT(gGrasslandPage29)}, 
	{gGrasslandPage30, ARRAY_COUNT(gGrasslandPage30)}, 
	{gGrasslandPage31, ARRAY_COUNT(gGrasslandPage31)}, 
	{gGrasslandPage32, ARRAY_COUNT(gGrasslandPage32)}, 
	{gGrasslandPage33, ARRAY_COUNT(gGrasslandPage33)}, 
	{gGrasslandPage34, ARRAY_COUNT(gGrasslandPage34)}, 
	{gGrasslandPage35, ARRAY_COUNT(gGrasslandPage35)}, 
	{gGrasslandPage36, ARRAY_COUNT(gGrasslandPage36)}, 
	{gGrasslandPage37, ARRAY_COUNT(gGrasslandPage37)}, 
	{gGrasslandPage38, ARRAY_COUNT(gGrasslandPage38)}, 
	{gGrasslandPage39, ARRAY_COUNT(gGrasslandPage39)}, 
	{gGrasslandPage40, ARRAY_COUNT(gGrasslandPage40)}, 
	{gGrasslandPage41, ARRAY_COUNT(gGrasslandPage41)}, 
	{gGrasslandPage42, ARRAY_COUNT(gGrasslandPage42)}, 
	{gGrasslandPage43, ARRAY_COUNT(gGrasslandPage43)}, 
	{gGrasslandPage44, ARRAY_COUNT(gGrasslandPage44)}, 
	{gGrasslandPage45, ARRAY_COUNT(gGrasslandPage45)}, 
	{gGrasslandPage46, ARRAY_COUNT(gGrasslandPage46)}, 
	{gGrasslandPage47, ARRAY_COUNT(gGrasslandPage47)}, 
	{gGrasslandPage48, ARRAY_COUNT(gGrasslandPage48)}, 
	{gGrasslandPage49, ARRAY_COUNT(gGrasslandPage49)}, 
	{gGrasslandPage50, ARRAY_COUNT(gGrasslandPage50)}, 
	{gGrasslandPage51, ARRAY_COUNT(gGrasslandPage51)}, 
	{gGrasslandPage52, ARRAY_COUNT(gGrasslandPage52)}, 
	{gGrasslandPage53, ARRAY_COUNT(gGrasslandPage53)}, 
	{gGrasslandPage54, ARRAY_COUNT(gGrasslandPage54)}, 
	{gGrasslandPage55, ARRAY_COUNT(gGrasslandPage55)}, 
	{gGrasslandPage56, ARRAY_COUNT(gGrasslandPage56)}, 
	{gGrasslandPage57, ARRAY_COUNT(gGrasslandPage57)}, 
};

const struct HabitatPage gForestPages[] =
{
	{gForestPage1, ARRAY_COUNT(gForestPage1)}, 
	{gForestPage2, ARRAY_COUNT(gForestPage2)}, 
	{gForestPage3, ARRAY_COUNT(gForestPage3)}, 
	{gForestPage4, ARRAY_COUNT(gForestPage4)}, 
	{gForestPage5, ARRAY_COUNT(gForestPage5)}, 
	{gForestPage6, ARRAY_COUNT(gForestPage6)}, 
	{gForestPage7, ARRAY_COUNT(gForestPage7)}, 
	{gForestPage8, ARRAY_COUNT(gForestPage8)}, 
	{gForestPage8_1, ARRAY_COUNT(gForestPage8_1)}, 
	{gForestPage8_2, ARRAY_COUNT(gForestPage8_2)}, 
	{gForestPage8_3, ARRAY_COUNT(gForestPage8_3)}, 
	{gForestPage8_4, ARRAY_COUNT(gForestPage8_4)}, 
	{gForestPage8_5, ARRAY_COUNT(gForestPage8_5)}, 
	{gForestPage9, ARRAY_COUNT(gForestPage9)}, 
	{gForestPage10, ARRAY_COUNT(gForestPage10)}, 
	{gForestPage11, ARRAY_COUNT(gForestPage11)}, 
	{gForestPage12, ARRAY_COUNT(gForestPage12)}, 
	{gForestPage13, ARRAY_COUNT(gForestPage13)}, 
	{gForestPage14, ARRAY_COUNT(gForestPage14)}, 
	{gForestPage15, ARRAY_COUNT(gForestPage15)}, 
	{gForestPage16, ARRAY_COUNT(gForestPage16)}, 
	{gForestPage17, ARRAY_COUNT(gForestPage17)}, 
	{gForestPage18, ARRAY_COUNT(gForestPage18)}, 
	{gForestPage19, ARRAY_COUNT(gForestPage19)}, 
	{gForestPage20, ARRAY_COUNT(gForestPage20)}, 
	{gForestPage21, ARRAY_COUNT(gForestPage21)}, 
	{gForestPage22, ARRAY_COUNT(gForestPage22)}, 
	{gForestPage23, ARRAY_COUNT(gForestPage23)}, 
	{gForestPage24, ARRAY_COUNT(gForestPage24)}, 
	{gForestPage25, ARRAY_COUNT(gForestPage25)}, 
	{gForestPage26, ARRAY_COUNT(gForestPage26)}, 
	{gForestPage27, ARRAY_COUNT(gForestPage27)}, 
	{gForestPage28, ARRAY_COUNT(gForestPage28)}, 
	{gForestPage29, ARRAY_COUNT(gForestPage29)}, 
	{gForestPage30, ARRAY_COUNT(gForestPage30)}, 
	{gForestPage31, ARRAY_COUNT(gForestPage31)}, 
	{gForestPage32, ARRAY_COUNT(gForestPage32)}, 
	{gForestPage33, ARRAY_COUNT(gForestPage33)}, 
	{gForestPage34, ARRAY_COUNT(gForestPage34)}, 
	{gForestPage35, ARRAY_COUNT(gForestPage35)}, 
	{gForestPage36, ARRAY_COUNT(gForestPage36)}, 
	{gForestPage37, ARRAY_COUNT(gForestPage37)}, 
	{gForestPage38, ARRAY_COUNT(gForestPage38)}, 
	{gForestPage39, ARRAY_COUNT(gForestPage39)}, 
	{gForestPage40, ARRAY_COUNT(gForestPage40)}, 
	{gForestPage41, ARRAY_COUNT(gForestPage41)}, 
	{gForestPage42, ARRAY_COUNT(gForestPage42)}, 
	{gForestPage43, ARRAY_COUNT(gForestPage43)}, 
	{gForestPage44, ARRAY_COUNT(gForestPage44)}, 
	{gForestPage45, ARRAY_COUNT(gForestPage45)}, 
	{gForestPage46, ARRAY_COUNT(gForestPage46)}, 
	{gForestPage47, ARRAY_COUNT(gForestPage47)}, 
	{gForestPage48, ARRAY_COUNT(gForestPage48)}, 
	{gForestPage49, ARRAY_COUNT(gForestPage49)}, 
	{gForestPage50, ARRAY_COUNT(gForestPage50)}, 
	{gForestPage51, ARRAY_COUNT(gForestPage51)}, 
	{gForestPage52, ARRAY_COUNT(gForestPage52)}, 
	{gForestPage53, ARRAY_COUNT(gForestPage53)}, 
	{gForestPage54, ARRAY_COUNT(gForestPage54)}, 
	{gForestPage55, ARRAY_COUNT(gForestPage55)}, 
	{gForestPage56, ARRAY_COUNT(gForestPage56)}, 
	{gForestPage57, ARRAY_COUNT(gForestPage57)}, 
	{gForestPage58, ARRAY_COUNT(gForestPage58)}, 
	{gForestPage59, ARRAY_COUNT(gForestPage59)},
	{gForestPage60, ARRAY_COUNT(gForestPage60)},
	{gForestPage61, ARRAY_COUNT(gForestPage61)},
	{gForestPage62, ARRAY_COUNT(gForestPage62)},
	{gForestPage63, ARRAY_COUNT(gForestPage63)},
	{gForestPage64, ARRAY_COUNT(gForestPage64)},
	{gForestPage65, ARRAY_COUNT(gForestPage65)},
};

const struct HabitatPage gWatersEdgePages[] =
{
	{gWatersEdgePage1, ARRAY_COUNT(gWatersEdgePage1)}, 
	{gWatersEdgePage2, ARRAY_COUNT(gWatersEdgePage2)}, 
	{gWatersEdgePage3, ARRAY_COUNT(gWatersEdgePage3)}, 
	{gWatersEdgePage4, ARRAY_COUNT(gWatersEdgePage4)}, 
	{gWatersEdgePage5, ARRAY_COUNT(gWatersEdgePage5)}, 
	{gWatersEdgePage6, ARRAY_COUNT(gWatersEdgePage6)}, 
	{gWatersEdgePage7, ARRAY_COUNT(gWatersEdgePage7)}, 
	{gWatersEdgePage8, ARRAY_COUNT(gWatersEdgePage8)}, 
	{gWatersEdgePage9, ARRAY_COUNT(gWatersEdgePage9)}, 
	{gWatersEdgePage10, ARRAY_COUNT(gWatersEdgePage10)}, 
	{gWatersEdgePage11, ARRAY_COUNT(gWatersEdgePage11)}, 
	{gWatersEdgePage12, ARRAY_COUNT(gWatersEdgePage12)}, 
	{gWatersEdgePage13, ARRAY_COUNT(gWatersEdgePage13)}, 
	{gWatersEdgePage14, ARRAY_COUNT(gWatersEdgePage14)}, 
	{gWatersEdgePage15, ARRAY_COUNT(gWatersEdgePage15)}, 
	{gWatersEdgePage16, ARRAY_COUNT(gWatersEdgePage16)}, 
	{gWatersEdgePage17, ARRAY_COUNT(gWatersEdgePage17)}, 
	{gWatersEdgePage18, ARRAY_COUNT(gWatersEdgePage18)}, 
	{gWatersEdgePage19, ARRAY_COUNT(gWatersEdgePage19)}, 
	{gWatersEdgePage20, ARRAY_COUNT(gWatersEdgePage20)}, 
	{gWatersEdgePage21, ARRAY_COUNT(gWatersEdgePage21)}, 
	{gWatersEdgePage22, ARRAY_COUNT(gWatersEdgePage22)}, 
	{gWatersEdgePage23, ARRAY_COUNT(gWatersEdgePage23)}, 
	{gWatersEdgePage24, ARRAY_COUNT(gWatersEdgePage24)}, 
	{gWatersEdgePage25, ARRAY_COUNT(gWatersEdgePage25)}, 
	{gWatersEdgePage26, ARRAY_COUNT(gWatersEdgePage26)}, 
	{gWatersEdgePage27, ARRAY_COUNT(gWatersEdgePage27)}, 
	{gWatersEdgePage28, ARRAY_COUNT(gWatersEdgePage28)}, 
	{gWatersEdgePage29, ARRAY_COUNT(gWatersEdgePage29)}, 
	{gWatersEdgePage30, ARRAY_COUNT(gWatersEdgePage30)}, 
	{gWatersEdgePage31, ARRAY_COUNT(gWatersEdgePage31)}, 
	{gWatersEdgePage32, ARRAY_COUNT(gWatersEdgePage32)}, 
	{gWatersEdgePage33, ARRAY_COUNT(gWatersEdgePage33)}, 
	{gWatersEdgePage34, ARRAY_COUNT(gWatersEdgePage34)}, 
	{gWatersEdgePage35, ARRAY_COUNT(gWatersEdgePage35)}, 
	{gWatersEdgePage36, ARRAY_COUNT(gWatersEdgePage36)},
	{gWatersEdgePage37, ARRAY_COUNT(gWatersEdgePage37)}, 
	{gWatersEdgePage38, ARRAY_COUNT(gWatersEdgePage38)}, 
};

const struct HabitatPage gSeaPages[] =
{
	{gSeaPage1, ARRAY_COUNT(gSeaPage1)}, 
	{gSeaPage2, ARRAY_COUNT(gSeaPage2)}, 
	{gSeaPage3, ARRAY_COUNT(gSeaPage3)}, 
	{gSeaPage4, ARRAY_COUNT(gSeaPage4)}, 
	{gSeaPage5, ARRAY_COUNT(gSeaPage5)}, 
	{gSeaPage6, ARRAY_COUNT(gSeaPage6)}, 
	{gSeaPage7, ARRAY_COUNT(gSeaPage7)}, 
	{gSeaPage8, ARRAY_COUNT(gSeaPage8)}, 
	{gSeaPage9, ARRAY_COUNT(gSeaPage9)}, 
	{gSeaPage10, ARRAY_COUNT(gSeaPage10)}, 
	{gSeaPage11, ARRAY_COUNT(gSeaPage11)}, 
	{gSeaPage12, ARRAY_COUNT(gSeaPage12)}, 
	{gSeaPage13, ARRAY_COUNT(gSeaPage13)}, 
	{gSeaPage14, ARRAY_COUNT(gSeaPage14)}, 
	{gSeaPage15, ARRAY_COUNT(gSeaPage15)}, 
	{gSeaPage16, ARRAY_COUNT(gSeaPage16)}, 
	{gSeaPage17, ARRAY_COUNT(gSeaPage17)}, 
	{gSeaPage18, ARRAY_COUNT(gSeaPage18)}, 
	{gSeaPage19, ARRAY_COUNT(gSeaPage19)}, 
	{gSeaPage20, ARRAY_COUNT(gSeaPage20)}, 
	{gSeaPage21, ARRAY_COUNT(gSeaPage21)}, 
	{gSeaPage22, ARRAY_COUNT(gSeaPage22)}, 
};

const struct HabitatPage gCavePages[] =
{
	{gCavePage1, ARRAY_COUNT(gCavePage1)}, 
	{gCavePage2, ARRAY_COUNT(gCavePage2)}, 
	{gCavePage3, ARRAY_COUNT(gCavePage3)}, 
	{gCavePage4, ARRAY_COUNT(gCavePage4)}, 
	{gCavePage5, ARRAY_COUNT(gCavePage5)}, 
	{gCavePage6, ARRAY_COUNT(gCavePage6)}, 
	{gCavePage7, ARRAY_COUNT(gCavePage7)}, 
	{gCavePage8, ARRAY_COUNT(gCavePage8)}, 
	{gCavePage9, ARRAY_COUNT(gCavePage9)}, 
	{gCavePage10, ARRAY_COUNT(gCavePage10)}, 
	{gCavePage11, ARRAY_COUNT(gCavePage11)}, 
	{gCavePage12, ARRAY_COUNT(gCavePage12)}, 
	{gCavePage13, ARRAY_COUNT(gCavePage13)}, 
	{gCavePage14, ARRAY_COUNT(gCavePage14)}, 
	{gCavePage15, ARRAY_COUNT(gCavePage15)}, 
	{gCavePage16, ARRAY_COUNT(gCavePage16)}, 
	{gCavePage17, ARRAY_COUNT(gCavePage17)}, 
	{gCavePage18, ARRAY_COUNT(gCavePage18)}, 
	{gCavePage19, ARRAY_COUNT(gCavePage19)}, 
	{gCavePage20, ARRAY_COUNT(gCavePage20)}, 
	{gCavePage21, ARRAY_COUNT(gCavePage21)}, 
	{gCavePage22, ARRAY_COUNT(gCavePage22)}, 
	{gCavePage23, ARRAY_COUNT(gCavePage23)}, 
	{gCavePage24, ARRAY_COUNT(gCavePage24)}, 
	{gCavePage25, ARRAY_COUNT(gCavePage25)}, 
	{gCavePage26, ARRAY_COUNT(gCavePage26)}, 
	{gCavePage27, ARRAY_COUNT(gCavePage27)}, 
	{gCavePage28, ARRAY_COUNT(gCavePage28)}, 
	{gCavePage29, ARRAY_COUNT(gCavePage29)}, 
	{gCavePage30, ARRAY_COUNT(gCavePage30)}, 
	{gCavePage31, ARRAY_COUNT(gCavePage31)}, 
	{gCavePage32, ARRAY_COUNT(gCavePage32)}, 
	{gCavePage33, ARRAY_COUNT(gCavePage33)}, 
	{gCavePage34, ARRAY_COUNT(gCavePage34)}, 
	{gCavePage35, ARRAY_COUNT(gCavePage35)}, 
};

const struct HabitatPage gMountainPages[] =
{
	{gMountainPage1, ARRAY_COUNT(gMountainPage1)}, 
	{gMountainPage2, ARRAY_COUNT(gMountainPage2)}, 
	{gMountainPage3, ARRAY_COUNT(gMountainPage3)}, 
	{gMountainPage4, ARRAY_COUNT(gMountainPage4)}, 
	{gMountainPage5, ARRAY_COUNT(gMountainPage5)}, 
	{gMountainPage6, ARRAY_COUNT(gMountainPage6)}, 
	{gMountainPage7, ARRAY_COUNT(gMountainPage7)}, 
	{gMountainPage8, ARRAY_COUNT(gMountainPage8)}, 
	{gMountainPage9, ARRAY_COUNT(gMountainPage9)}, 
	{gMountainPage10, ARRAY_COUNT(gMountainPage10)}, 
	{gMountainPage11, ARRAY_COUNT(gMountainPage11)}, 
	{gMountainPage12, ARRAY_COUNT(gMountainPage12)}, 
	{gMountainPage13, ARRAY_COUNT(gMountainPage13)}, 
	{gMountainPage14, ARRAY_COUNT(gMountainPage14)}, 
	{gMountainPage15, ARRAY_COUNT(gMountainPage15)}, 
	{gMountainPage16, ARRAY_COUNT(gMountainPage16)}, 
	{gMountainPage17, ARRAY_COUNT(gMountainPage17)}, 
	{gMountainPage18, ARRAY_COUNT(gMountainPage18)}, 
	{gMountainPage19, ARRAY_COUNT(gMountainPage19)}, 
	{gMountainPage20, ARRAY_COUNT(gMountainPage20)}, 
	{gMountainPage21, ARRAY_COUNT(gMountainPage21)}, 
	{gMountainPage22, ARRAY_COUNT(gMountainPage22)}, 
	{gMountainPage23, ARRAY_COUNT(gMountainPage23)}, 
	{gMountainPage24, ARRAY_COUNT(gMountainPage24)}, 
	{gMountainPage25, ARRAY_COUNT(gMountainPage25)}, 
	{gMountainPage26, ARRAY_COUNT(gMountainPage26)}, 
	{gMountainPage27, ARRAY_COUNT(gMountainPage27)}, 
	{gMountainPage28, ARRAY_COUNT(gMountainPage28)}, 
	{gMountainPage29, ARRAY_COUNT(gMountainPage29)}, 
	{gMountainPage30, ARRAY_COUNT(gMountainPage30)}, 
	{gMountainPage31, ARRAY_COUNT(gMountainPage31)}, 
	{gMountainPage32, ARRAY_COUNT(gMountainPage32)}, 
	{gMountainPage33, ARRAY_COUNT(gMountainPage33)}, 
	{gMountainPage34, ARRAY_COUNT(gMountainPage34)}, 
	{gMountainPage35, ARRAY_COUNT(gMountainPage35)}, 
	{gMountainPage36, ARRAY_COUNT(gMountainPage36)},
	{gMountainPage37, ARRAY_COUNT(gMountainPage37)},
	{gMountainPage38, ARRAY_COUNT(gMountainPage38)},
	{gMountainPage39, ARRAY_COUNT(gMountainPage39)},
	{gMountainPage40, ARRAY_COUNT(gMountainPage40)},
	{gMountainPage41, ARRAY_COUNT(gMountainPage41)},
	{gMountainPage42, ARRAY_COUNT(gMountainPage42)},
	{gMountainPage43, ARRAY_COUNT(gMountainPage43)},
};

const struct HabitatPage gRoughTerrainPages[] =
{
	{gRoughTerrainPage1, ARRAY_COUNT(gRoughTerrainPage1)}, 
	{gRoughTerrainPage2, ARRAY_COUNT(gRoughTerrainPage2)}, 
	{gRoughTerrainPage3, ARRAY_COUNT(gRoughTerrainPage3)}, 
	{gRoughTerrainPage4, ARRAY_COUNT(gRoughTerrainPage4)}, 
	{gRoughTerrainPage5, ARRAY_COUNT(gRoughTerrainPage5)}, 
	{gRoughTerrainPage6, ARRAY_COUNT(gRoughTerrainPage6)}, 
	{gRoughTerrainPage7, ARRAY_COUNT(gRoughTerrainPage7)}, 
	{gRoughTerrainPage8, ARRAY_COUNT(gRoughTerrainPage8)}, 
	{gRoughTerrainPage9, ARRAY_COUNT(gRoughTerrainPage9)}, 
	{gRoughTerrainPage10, ARRAY_COUNT(gRoughTerrainPage10)}, 
	{gRoughTerrainPage11, ARRAY_COUNT(gRoughTerrainPage11)}, 
	{gRoughTerrainPage12, ARRAY_COUNT(gRoughTerrainPage12)}, 
	{gRoughTerrainPage13, ARRAY_COUNT(gRoughTerrainPage13)}, 
	{gRoughTerrainPage14, ARRAY_COUNT(gRoughTerrainPage14)}, 
	{gRoughTerrainPage15, ARRAY_COUNT(gRoughTerrainPage15)}, 
	{gRoughTerrainPage16, ARRAY_COUNT(gRoughTerrainPage16)}, 
	{gRoughTerrainPage17, ARRAY_COUNT(gRoughTerrainPage17)}, 
	{gRoughTerrainPage18, ARRAY_COUNT(gRoughTerrainPage18)}, 
	{gRoughTerrainPage19, ARRAY_COUNT(gRoughTerrainPage19)}, 
	{gRoughTerrainPage20, ARRAY_COUNT(gRoughTerrainPage20)}, 
	{gRoughTerrainPage21, ARRAY_COUNT(gRoughTerrainPage21)}, 
	{gRoughTerrainPage22, ARRAY_COUNT(gRoughTerrainPage22)}, 
	{gRoughTerrainPage23, ARRAY_COUNT(gRoughTerrainPage23)}, 
	{gRoughTerrainPage24, ARRAY_COUNT(gRoughTerrainPage24)}, 
	{gRoughTerrainPage25, ARRAY_COUNT(gRoughTerrainPage25)}, 
	{gRoughTerrainPage26, ARRAY_COUNT(gRoughTerrainPage26)}, 
	{gRoughTerrainPage27, ARRAY_COUNT(gRoughTerrainPage27)}, 
	{gRoughTerrainPage28, ARRAY_COUNT(gRoughTerrainPage28)}, 
};

const struct HabitatPage gUrbanPages[] =
{
	{gUrbanPage1, ARRAY_COUNT(gUrbanPage1)}, 
	{gUrbanPage2, ARRAY_COUNT(gUrbanPage2)}, 
	{gUrbanPage3, ARRAY_COUNT(gUrbanPage3)}, 
	{gUrbanPage4, ARRAY_COUNT(gUrbanPage4)}, 
	{gUrbanPage5, ARRAY_COUNT(gUrbanPage5)}, 
	{gUrbanPage6, ARRAY_COUNT(gUrbanPage6)}, 
	{gUrbanPage7, ARRAY_COUNT(gUrbanPage7)}, 
	{gUrbanPage8, ARRAY_COUNT(gUrbanPage8)}, 
	{gUrbanPage9, ARRAY_COUNT(gUrbanPage9)}, 
	{gUrbanPage10, ARRAY_COUNT(gUrbanPage10)}, 
	{gUrbanPage11, ARRAY_COUNT(gUrbanPage11)}, 
	{gUrbanPage12, ARRAY_COUNT(gUrbanPage12)}, 
	{gUrbanPage13, ARRAY_COUNT(gUrbanPage13)}, 
	{gUrbanPage14, ARRAY_COUNT(gUrbanPage14)}, 
	{gUrbanPage15, ARRAY_COUNT(gUrbanPage15)}, 
	{gUrbanPage16, ARRAY_COUNT(gUrbanPage16)}, 
	{gUrbanPage17, ARRAY_COUNT(gUrbanPage17)}, 
	{gUrbanPage18, ARRAY_COUNT(gUrbanPage18)}, 
	{gUrbanPage19, ARRAY_COUNT(gUrbanPage19)}, 
	{gUrbanPage20, ARRAY_COUNT(gUrbanPage20)}, 
	{gUrbanPage21, ARRAY_COUNT(gUrbanPage21)}, 
	{gUrbanPage22, ARRAY_COUNT(gUrbanPage22)}, 
	{gUrbanPage23, ARRAY_COUNT(gUrbanPage23)}, 
	{gUrbanPage24, ARRAY_COUNT(gUrbanPage24)}, 
	{gUrbanPage25, ARRAY_COUNT(gUrbanPage25)}, 
	{gUrbanPage26, ARRAY_COUNT(gUrbanPage26)}, 
	{gUrbanPage27, ARRAY_COUNT(gUrbanPage27)}, 
	{gUrbanPage28, ARRAY_COUNT(gUrbanPage28)}, 
	{gUrbanPage29, ARRAY_COUNT(gUrbanPage29)}, 
	{gUrbanPage30, ARRAY_COUNT(gUrbanPage30)}, 
	{gUrbanPage31, ARRAY_COUNT(gUrbanPage31)}, 
	{gUrbanPage32, ARRAY_COUNT(gUrbanPage32)}, 
	{gUrbanPage33, ARRAY_COUNT(gUrbanPage33)}, 
	{gUrbanPage34, ARRAY_COUNT(gUrbanPage34)}, 
	{gUrbanPage35, ARRAY_COUNT(gUrbanPage35)}, 
	{gUrbanPage36, ARRAY_COUNT(gUrbanPage36)},
	{gUrbanPage37, ARRAY_COUNT(gUrbanPage37)}, 
};

const struct HabitatPage gRarePages[] =
{
	{gRarePage1, ARRAY_COUNT(gRarePage1)}, 
	{gRarePage2, ARRAY_COUNT(gRarePage2)}, 
	{gRarePage3, ARRAY_COUNT(gRarePage3)}, 
	{gRarePage4, ARRAY_COUNT(gRarePage4)}, 
	{gRarePage5, ARRAY_COUNT(gRarePage5)}, 
	{gRarePage6, ARRAY_COUNT(gRarePage6)}, 
	{gRarePage7, ARRAY_COUNT(gRarePage7)}, 
	{gRarePage8, ARRAY_COUNT(gRarePage8)}, 
	{gRarePage9, ARRAY_COUNT(gRarePage9)}, 
	{gRarePage10, ARRAY_COUNT(gRarePage10)}, 
	{gRarePage11, ARRAY_COUNT(gRarePage11)}, 
	{gRarePage12, ARRAY_COUNT(gRarePage12)}, 
	{gRarePage13, ARRAY_COUNT(gRarePage13)}, 
	{gRarePage14, ARRAY_COUNT(gRarePage14)}, 
	{gRarePage15, ARRAY_COUNT(gRarePage15)}, 
	{gRarePage16, ARRAY_COUNT(gRarePage16)}, 
	{gRarePage17, ARRAY_COUNT(gRarePage17)}, 
	{gRarePage18, ARRAY_COUNT(gRarePage18)},
	{gRarePage19, ARRAY_COUNT(gRarePage19)},
	{gRarePage20, ARRAY_COUNT(gRarePage20)},
	{gRarePage21, ARRAY_COUNT(gRarePage21)},
	{gRarePage22, ARRAY_COUNT(gRarePage22)},
	{gRarePage23, ARRAY_COUNT(gRarePage23)},
	{gRarePage24, ARRAY_COUNT(gRarePage24)},
	{gRarePage25, ARRAY_COUNT(gRarePage25)},
	{gRarePage26, ARRAY_COUNT(gRarePage26)},
	{gRarePage27, ARRAY_COUNT(gRarePage27)},
	{gRarePage28, ARRAY_COUNT(gRarePage28)},
	{gRarePage29, ARRAY_COUNT(gRarePage29)},
	{gRarePage30, ARRAY_COUNT(gRarePage30)},
	{gRarePage31, ARRAY_COUNT(gRarePage31)},
	{gRarePage32, ARRAY_COUNT(gRarePage32)},
	{gRarePage33, ARRAY_COUNT(gRarePage33)},
	{gRarePage34, ARRAY_COUNT(gRarePage34)},
};

const struct Habitat gHabitatPtrsTable[9] =
{
	{gGrasslandPages, ARRAY_COUNT(gGrasslandPages)},
	{gForestPages, ARRAY_COUNT(gForestPages)},
	{gWatersEdgePages, ARRAY_COUNT(gWatersEdgePages)},
	{gSeaPages, ARRAY_COUNT(gSeaPages)},
	{gCavePages, ARRAY_COUNT(gCavePages)},
	{gMountainPages, ARRAY_COUNT(gMountainPages)},
	{gRoughTerrainPages, ARRAY_COUNT(gRoughTerrainPages)},
	{gUrbanPages, ARRAY_COUNT(gUrbanPages)},
	{gRarePages, ARRAY_COUNT(gRarePages)},
};
